### ISSUE TITLE
Allow to modify the header

### ISSUE THREAD

**Issue by sagikazarmark** [middlewares/uuid#1]
IMHO the name `X-Uuid` is not really a good choice and I would like to change it to `X-Request-ID` or `X-Correlation-ID` as they at least mean something.

On the other hand this middleware is probably not the biggest one, so just copying some code might be the solution.

**Comment by oscarotero** [comment]
Good idea 👍 
I've released v0.4.0 with the`header()` option.

**Comment by sagikazarmark** [comment]
Wow, that was fast. 👍
